### ISSUE TITLE
Errors when trying to run default example

### ISSUE THREAD

**Issue by janelleshane** [mouse-reeve/ozymandias#1]
Hi! I'm getting the following error on OSX when I try to run the default example:
Command: ./the_decay_of_that_colossal_wreck.sh
Error:

--- Iteration 1 ---
Using font: 
convert: unable to read font `' @ warning/annotate.c/RenderType/924.
convert: unable to read font `' @ error/annotate.c/RenderFreetype/1239.
convert: unable to read font `' @ warning/annotate.c/RenderType/924.
convert: unable to read font `' @ error/annotate.c/RenderFreetype/1239.
convert: geometry does not contain image `white' @ warning/attribute.c/GetImageBoundingBox/247.
convert: unable to load module `/usr/local/Cellar/imagemagick/6.9.3-0_2/lib/ImageMagick//modules-Q16/coders/png.la': file not found @ error/module.c/OpenModule/1300.
convert: no encode delegate for this image format `XC' @ error/constitute.c/WriteImage/1167.
Tesseract Open Source OCR Engine v3.05.01 with Leptonica
Error in fopenReadStream: file not found
Error in findFileFormat: image file not found
Error during processing.
rm: ozymandias-1.png: No such file or directory

**Comment by mouse-reeve** [comment]
Sounds like it isn't successfully finding fonts. Can you run `convert -list font` in the command line and tell me what the output is?

**Comment by janelleshane** [comment]
Thanks for your response! In the meantime I tried upgrading imagemagick, and it looks like that did the trick! It's running successfully now.

(Haha, webdings is in the list? That'll be a tricky one)

**Comment by mouse-reeve** [comment]
Yay, glad it's resolved! The script actually omits fonts that start with "W" to avoid Webdings and Wingdins 😂
